baseURL = 'https://swsmith.cc/'
languageCode = 'en-us'
title = "Sean Smith 🚀"
uglyurls = true

# theme
theme="archie"

# google analytics
googleAnalytics = "G-3HSS44JHGS"

# disqus comments
disqusShortname = "swsmith-cc"

[params]
subtitle = "Blog that's mostly made up with my [Github Gists](https://gist.github.com/sean-smith)"
og_image = "/img/sean.jpg"
customJS = ['js/section-link.js']

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sean-smith"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/seanwssmith/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/seanfliesthings"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/seanwssmith/"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:sean@swsmith.cc"


# Main menu Items

[[menu.main]]
name = "Posts"
url = "/posts.html"
weight = 1

[[menu.main]]
name = "About"
url = "/about.html"
weight = 2

[[menu.main]]
name = "Websites"
url = "/websites.html"
weight = 3

[[menu.main]]
name = "Slides"
url = "/slides.html"
weight = 4
